//  <auto-generated/>

using System;
using System.Collections;

namespace PnpMemory
{
    public  class diagnosticResults
    {
        public Hashtable Map { get; set; } = new Hashtable();
        public int Status { get; set; }
    }
}
